### PR TITLE
Jei Improvements

### LINKED ISSUE #2570: Botania, JEI and Crafting Station crash
My crafting station was placed beside the petal apothecary from Botania and it recognized the internal slots as a chest in the GUI.

Since I couldn't click to insert or take items from the slots I just assumed it was fine since it respected the isValidItem/canTake methods on those slots.

But then I tried to click the plus sign on a recipe in JEI and since the crafring station wasnt empty it tried to move the items in to the slots of the petal apothecary and since those items should never be in there it crashed the game.

Hopefully a not too confusing screenshot:

Now afaik JEI is at fault but I reported it in all three repos:
https://github.com/SlimeKnights/TinkersConstruct/issues/2570
https://github.com/mezz/JustEnoughItems/issues/615
https://github.com/Vazkii/Botania/issues/2036

```
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassCastException: net.minecraft.item.Item cannot be cast to vazkii.botania.api.recipe.IFlowerComponent
	at vazkii.botania.common.block.tile.TileAltar.func_73660_a(TileAltar.java:263) ~[TileAltar.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
```

Relevant versions:
- Forge{12.18.2.2125} [Minecraft Forge] (forge-1.10.2-12.18.2.2125.jar) 
- mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
- tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
- JEI{3.13.3.372} [Just Enough Items] (jei_1.10.2-3.13.3.372.jar) 
- Botania{r1.9-337} [Botania] (Botania r1.9-337.jar)

### PR DESCRIPTION
**Pull request by KnightMiner**
The following four commits are a collection of fixes and improvements for JEI. Specific changes are listed below:

* Fluids in the tinker tank and smeltery GUIs now support fluid recipe and usage lookup by pressing "R" and "U".
* Added subtype information for patterns, casts, tables, racks, and tool parts. In addition, when viewing a table recipe, it will now animate through all available tables by default, and just the relevant recipe if a table is in focus (item transfer still allows any wood to be pulled from the inventory)
* Fixed #2570 by preventing the item transfer from placing items in the side inventory
* Added a version dependency for JEI. If it is loaded, it must have what is currently the latest build, 3.13.6.387, as I use API methods from that build.
* Fixes only wood showing on cast creation recipes

### CODE REVIEW

File: src/main/java/slimeknights/tconstruct/tools/common/item/ItemBlockTable.java [hunk 1]
```diff
@@ -43,6 +43,23 @@ public void addInformation(@Nonnull ItemStack stack, @Nonnull EntityPlayer playe
     }
   }
 
+  /**
+   * Gets the itemstack that determines the leg's texture from the table
+   * @param table  Input table
+   * @return  The itemstack determining the leg's texture, or null if none exists
+   */
+  public static ItemStack getLegStack(ItemStack table) {
```
Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/tools/common/item/ItemBlockTable.java]: Yes. :+1:

File: src/main/java/slimeknights/tconstruct/smeltery/client/IGuiLiquidTank.java [hunk 2]
```diff
@@ -0,0 +1,7 @@
+package slimeknights.tconstruct.smeltery.client;
```
Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/smeltery/client/IGuiLiquidTank.java]: Abstracted that stuff away behind an interface, good :+1:

File: src/main/java/slimeknights/tconstruct/library/client/GuiUtil.java [hunk 3]
```diff
@@ -153,6 +153,22 @@ public static void drawGuiTank(SmelteryTank liquids, int x, int y, int w, int he
     }
   }
 
+  public static FluidStack getFluidStackAtPosition(SmelteryTank tank, int mouseX, int mouseY, int xmin, int ymin, int xmax, int ymax) {
```
Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/library/client/GuiUtil.java]: That is quite literally exactly the same thing as the handleTankClick function below. I'll fix up handleTankClick after pulling the PR

File: src/main/java/slimeknights/tconstruct/plugin/jei/JEIPlugin.java [hunk 4]
```diff
@@ -30,20 +34,58 @@
...
+
+    // tools
+    if(TConstruct.pulseManager.isPulseLoaded(TinkerTools.PulseId)) {
+      // tool tables
+      registry.registerSubtypeInterpreter(Item.getItemFromBlock(TinkerTools.toolTables), tableInterpreter);
+      registry.registerSubtypeInterpreter(Item.getItemFromBlock(TinkerTools.toolForge), tableInterpreter);
+
+      // tool parts
+      ToolPartSubtypeInterpreter toolPartInterpreter = new ToolPartSubtypeInterpreter();
+      for(IToolPart part : TinkerRegistry.getToolParts()) {
```
Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/plugin/jei/JEIPlugin.java]: For the future, since we're using Java8 now, we can use foreach + filter very well for things like this

File: src/main/java/slimeknights/tconstruct/plugin/jei/TableSubtypeInterpreter.java [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+  @Override
+  public String getSubtypeInfo(ItemStack stack) {
+    // we have to handle the metadata here
+    String meta = stack.getMetadata() + ":";
+
+    // if the legs exist, return that for the identification key
+    NBTTagCompound tag = TagUtil.getTagSafe(stack).getCompoundTag(TileTable.FEET_TAG);
+    ItemStack legs = ItemStack.loadItemStackFromNBT(tag);
+    if(legs != null && legs.getItem() != null) {
+      return meta + legs.getItem().getRegistryName() + ":" + legs.getMetadata();
```
Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/plugin/jei/TableSubtypeInterpreter.java]: meta += is better here than returning. Single exit point.

File: src/main/java/slimeknights/tconstruct/plugin/jei/ToolPartSubtypeInterpreter.java [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+
+// Handles all Tinker tool parts subtypes
+public class ToolPartSubtypeInterpreter implements ISubtypeInterpreter {
+
+  @Override
+  public String getSubtypeInfo(ItemStack stack) {
+    String meta = stack.getItemDamage() + ":";
+
+    Material material = TinkerUtil.getMaterialFromStack(stack);
+    if(material == null) {
```
Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/plugin/jei/ToolPartSubtypeInterpreter.java]: Same as above, if != null meta +=

File: src/main/java/slimeknights/tconstruct/library/client/GuiUtil.java (hunk 3 above)
Comment (KnightMiner) [inline src/main/java/slimeknights/tconstruct/library/client/GuiUtil.java]: Nearly, the main difference is the code in the exactiddle changed, and I was not sure of the cleanest way to do that.

Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/library/client/GuiUtil.java]: What is that change? I extracted the common stuff and didn't notice any missing behaviour, was it an edge case?

Comment (KnightMiner) [inline src/main/java/slimeknights/tconstruct/library/client/GuiUtil.java]: Nope, just did not think to return an integer and pass that along :)
