### PR TITLE
Fix #3702

### LINKED ISSUE #3702: Smeltery Forming and unforming causing a client freeze
**Issue description:**

If you build a 4x1 smeltery (or larger) with the controller on the base, level (Floor), a tank above it and a drain to the right, formed like so

X=Seared Brick | C=Controller | T=Tank | D=Drain | A=AIR

Y=1
XXXXXX
XXXXXX
XXCXXX

Y=2
XXXXXX
XAAAAX
XXTDXX

And break one of the seared brick on the upper level, the smeltery will form and unform, causing the liquid to render and unrender causing the client to lag and completely freeze. using a mod to force the smeltery to not render the liquid resolves this issue.

**If crashed, link to crash report (use a site such as pastebin):**
https://gist.github.com/850ed18f47d86c481045e086a611348f

**Versions:**
* Minecraft:  1.12.2
* Forge: 2772
* Mantle: 1.3.3.39
* Tinkers Construct: 10.1.87
* SpongeForge: RC3505

**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Requires a dedicated server with sponge. (tested on the latest version of DW20)

### PR DESCRIPTION
**Pull request by LXGaming**
Prevents Multiblock structures from becoming active if a BlockMultiblockController Y position is equal to or lower than the floor layer

### CODE REVIEW

File: src/main/java/slimeknights/tconstruct/smeltery/multiblock/MultiblockCuboid.java [hunk 1]
```diff
@@ -71,6 +71,11 @@ public MultiblockStructure detectMultiblock(World world, BlockPos center, int li
       }
     }
 
+    // below lowest internal position
```
Comment (bonii-xx) [inline src/main/java/slimeknights/tconstruct/smeltery/multiblock/MultiblockCuboid.java]: Good analysis and correct fix. However you should move the check up directly after the center is calculated (Line 40).

Comment (LXGaming) [reply src/main/java/slimeknights/tconstruct/smeltery/multiblock/MultiblockCuboid.java]: Good point, Done.
